<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller; use App\Http\Requests\StoreProductRequest; use App\Http\Requests\UpdateProductRequest; use App\Http\Requests\UpdateProductStatusRequest; use App\Repositories\MySqlProductRepository; use App\Services\AdminAuditService; use App\Services\ProductImageStore; use App\Services\PersistenceException; use Illuminate\Http\JsonResponse; use Illuminate\Support\Facades\Log;
class ProductController extends Controller {
 public function index(MySqlProductRepository $repository): JsonResponse { try{$products=array_map(fn($p)=>$this->view($p),$repository->all());}catch(\Throwable){return $this->unavailable();}usort($products,fn($a,$b)=>$a['id']<=>$b['id']);return response()->json(['products'=>$products]); }
 public function store(StoreProductRequest $r,MySqlProductRepository $repository,ProductImageStore $images,AdminAuditService $audit):JsonResponse{$path=null;try{$path=$r->hasFile('image')?$images->store($r->file('image')):null;$v=$r->validated();$p=$repository->create(['name'=>trim($v['name']),'category_id'=>$v['category_id'],'subcategory_id'=>$v['subcategory_id'],'presentation'=>trim($v['presentation']),'price_cop'=>$v['price'],'inventory'=>$v['inventory'],'active'=>(bool)$v['active'],'image_path'=>$path,'legacy_img'=>null]);}catch(PersistenceException $e){if($path)$images->forget($path);return $this->error($e);}catch(\Throwable){if($path)$images->forget($path);return response()->json(['message'=>'No fue posible guardar el producto.'],503);}$audit->record($r,'CREATE','PRODUCT',$p['product_id'],[],$this->view($p));return $this->commit($p,$repository);}
 public function update(int $id,UpdateProductRequest $r,MySqlProductRepository $repository,ProductImageStore $images,AdminAuditService $audit):JsonResponse{$before=[];try{$before=$repository->findById($id)['product']??[];}catch(\Throwable){}$path=null;try{$path=$r->hasFile('image')?$images->store($r->file('image')):null;$v=$r->validated();$changes=['name'=>trim($v['name']),'category_id'=>$v['category_id'],'subcategory_id'=>$v['subcategory_id'],'presentation'=>trim($v['presentation']),'price_cop'=>$v['price'],'inventory'=>$v['inventory']];if($path)$changes['image_path']=$path;$p=$repository->update($id,$v['expected_revision'],$changes);}catch(PersistenceException $e){$this->logProductFailure('update',$id,$e);if($path)$images->forget($path);return $this->error($e);}catch(\Throwable $e){$this->logProductFailure('update',$id,$e);if($path)$images->forget($path);return response()->json(['message'=>'No fue posible guardar el producto.'],503);}$audit->record($r,'UPDATE','PRODUCT',$id,$before,$this->view($p));return $this->commit($p,$repository);}
 public function updateStatus(int $id,UpdateProductStatusRequest $r,MySqlProductRepository $repository,AdminAuditService $audit):JsonResponse{$before=[];try{$before=$repository->findById($id)['product']??[];}catch(\Throwable){}$v=$r->validated();try{$p=$repository->setActive($id,$v['expected_revision'],(bool)$v['active']);}catch(PersistenceException $e){return $this->error($e);}$audit->record($r,$p['active']?'ACTIVATE':'DEACTIVATE','PRODUCT',$id,['active'=>$before['active']??null],['active'=>$p['active']],$p['name']);return $this->commit($p,$repository);}
 private function commit(array $p,MySqlProductRepository $repository):JsonResponse{return response()->json(['product'=>$this->view($p),'catalog_refreshed'=>true,'sync_status'=>$repository->syncStatus()]);}
 private function view(array $p):array{return ['id'=>$p['product_id'],'category_id'=>$p['category_id']??null,'subcategory_id'=>$p['subcategory_id']??null,'img'=>$p['legacy_img'],'category'=>$p['category'],'subcategory'=>$p['subcategory'],'name'=>$p['name'],'presentation'=>$p['presentation'],'price'=>$p['price_cop'],'image'=>$p['image_path'],'inventory'=>$p['inventory'],'active'=>$p['active'],'revision'=>$p['revision']];}
 private function error(PersistenceException $e):JsonResponse{return response()->json(['message'=>$e->status()===409?'El producto cambio; actualiza el catalogo e intenta nuevamente.':'No fue posible guardar el producto.'],$e->status());}
 private function unavailable():JsonResponse{return response()->json(['message'=>'El catalogo no esta disponible en este momento.'],503,['Retry-After'=>'60']);}
 private function logProductFailure(string $operation,int $productId,\Throwable $e):void{$previous=$e->getPrevious();$apiStatus=null;if($previous&&method_exists($previous,'getResponse')&&$previous->getResponse())$apiStatus=$previous->getResponse()->getStatusCode();elseif($previous&&method_exists($previous,'getCode')&&$previous->getCode()>0)$apiStatus=$previous->getCode();Log::warning('MySQL product update failed.',['operation'=>$operation,'product_id'=>$productId,'exception_class'=>$e::class,'remote_code'=>$e instanceof PersistenceException?$e->remoteCode():null,'message'=>$this->sanitize($e->getMessage()),'previous_exception_class'=>$previous? $previous::class:null,'previous_message'=>$previous?$this->sanitize($previous->getMessage()):null,'database_status'=>$apiStatus]);}
 private function sanitize(string $message):string{$message=preg_replace('#https?://[^\s]+#i','[REDACTED]',$message)??'';return mb_strimwidth(trim(str_replace(["\r","\n"],' ',$message)),0,500,'...')?:'unavailable';}
}
