<?php
namespace App\Services;
use App\Promotions\{ProductPromotionNormalizer,ProductPromotionPriceResolver,PromotionContractException};
use App\Repositories\{MySqlProductRepository,MySqlProductPromotionRepository};
use DateTimeImmutable; use DateTimeZone;
final class ProductPromotionAdminService {
 public function __construct(private readonly MySqlProductRepository $products,private readonly MySqlProductPromotionRepository $promotions,private readonly ProductPromotionPriceResolver $prices){}
 public function show(int $id):array{return $this->view($this->product($id),$this->promotions->findByProductId($id));}
 public function list():array{$by=[];foreach($this->products->all() as $p)$by[$p['product_id']]=$p;$rows=[];foreach($this->promotions->all() as $promotion){$product=$by[$promotion['product_id']]??null;if($product===null)throw new PersistenceException(502,'PROMOTION_PRODUCT_NOT_FOUND',null,'Una promoción apunta a un producto inexistente.');$view=$this->view($product,$promotion);$rows[]=['product'=>['id'=>$product['product_id'],'name'=>$product['name'],'price'=>$product['price_cop'],'active'=>$product['active']],'promotion'=>$view['promotion'],'status'=>$view['status'],'pricing'=>$view['pricing']];}usort($rows,static fn($a,$b)=>strnatcasecmp($a['product']['name'],$b['product']['name']));return $rows;}
 public function save(int $id,array $input):array{$product=$this->product($id);$now=new DateTimeImmutable('now',new DateTimeZone('UTC'));try{$candidate=ProductPromotionNormalizer::normalize(['product_id'=>$id,'active'=>$input['active'],'discount_type'=>$input['discount_type'],'discount_value'=>$input['discount_value'],'starts_at'=>$input['starts_at']??null,'ends_at'=>$input['ends_at']??null,'updated_at'=>$now->format('Y-m-d\\TH:i:s.v\\Z'),'revision'=>1]);$this->prices->resolve($product['price_cop'],array_replace($candidate,['active'=>true,'starts_at'=>null,'ends_at'=>null]),$now);}catch(PromotionContractException $e){throw new PersistenceException(422,'INVALID_PROMOTION',$e,$e->getMessage());}$saved=$this->promotions->save($candidate,$input['expected_revision']??null);return [...$this->view($product,$saved),'catalog_refreshed'=>true];}
 private function view(array $product,?array $promotion):array{$now=new DateTimeImmutable('now',new DateTimeZone('UTC'));try{$pricing=$this->prices->resolve($product['price_cop'],$promotion,$now);}catch(PromotionContractException $e){throw new PersistenceException(502,'INVALID_PROMOTION_PRICE',$e,'La promoción guardada no es compatible con el precio base actual.');}$status=$promotion===null?'NONE':(!$promotion['active']?'INACTIVE':(($promotion['starts_at']!==null&&$now->setTimezone(new DateTimeZone('America/Bogota'))<new DateTimeImmutable($promotion['starts_at']))?'SCHEDULED':(($promotion['ends_at']!==null&&$now->setTimezone(new DateTimeZone('America/Bogota'))>new DateTimeImmutable($promotion['ends_at']))?'EXPIRED':'ACTIVE')));return ['product_id'=>$product['product_id'],'product_name'=>$product['name'],'promotion'=>$promotion,'status'=>$status,'pricing'=>$pricing];}
 private function product(int $id):array{$record=$this->products->findById($id);if($record===null)throw new PersistenceException(404,'PRODUCT_NOT_FOUND',null,'El producto no existe.');return $record['product'];}
}
