<?php

namespace Tests\Unit\Repositories;

use App\Contracts\GoogleSheetsValuesClient;
use App\Exceptions\CheckoutConsistencyException;
use App\Repositories\CheckoutSheetsRepository;
use Tests\TestCase;

final class CheckoutReleaseWritePrimitivesTest extends TestCase
{
    private const B='2026-09-25T12:00:00.111Z'; private const A='2026-09-25T12:10:00.111Z';
    private function client():object{return new class($this->tables()) implements GoogleSheetsValuesClient {public int $writes=0;public function __construct(public array $tables){}public function getValues(string $range):array{return [];}public function batchGetValues(array $ranges):array{return array_map(function($range){$sheet=explode('!',$range)[0];return str_ends_with($range,'1:1')?[array_values($this->tables[$sheet][0])]:$this->tables[$sheet];},$ranges);}public function updateValues(string $range,array $values):array{$this->writes++;preg_match('/^([^!]+)!A(\d+):/',$range,$m);$this->tables[$m[1]][(int)$m[2]-1]=$values[0];return [];}public function appendValues(string $range,array $values):array{return [];}public function batchUpdateValues(array $data):array{return [];}};}
    private function tables():array{return ['Productos'=>[['product_id','category','subcategory','name','presentation','price_cop','inventory','active','image_path','legacy_img','created_at','updated_at','revision'],[7,'C','S','P','U',100,1,true,'','',self::B,self::B,1]],'Pedidos'=>[['order_id','reference','status','payment_status','reservation_status','reservation_expires_at','paid_at','payment_last_event_at','checkout_idempotency_key','checkout_payload_hash','release_id','release_fingerprint','released_at','customer_name','customer_email','customer_phone','customer_document','address','extra','city','region','postal','total_cop','created_at','updated_at','revision'],[17,'TTV-TEST','PENDING','PENDING','ACTIVE','2026-09-25T11:00:00.111Z','','','11111111-1111-4111-8111-111111111111',str_repeat('a',64),'','','','N','a@b.co','1','1','D','','C','R','',100,self::B,self::B,1]],'PedidoItems'=>[['order_item_id','order_id','product_id','product_name','unit_price_cop','quantity','created_at']],'Pagos'=>[['payment_attempt_id','order_id','wompi_transaction_id','status','payment_method','amount_in_cents','currency','created_at','updated_at'],[1,17,'tx-1','PENDING','CARD',100,'COP',self::B,self::B]]];}
    private function paymentPlan():array{return ['row_number'=>2,'payment_attempt_id'=>1,'order_id'=>17,'wompi_transaction_id'=>'tx-1','status_before'=>'PENDING','status_after'=>'DECLINED','payment_method'=>'CARD','amount_in_cents'=>100,'currency'=>'COP','created_at'=>self::B,'updated_at_before'=>self::B,'updated_at_after'=>self::A];}
    private function orderPlan():array{return ['order_id'=>17,'reference'=>'TTV-TEST','status_before'=>'PENDING','status_after'=>'PENDING','payment_status_before'=>'PENDING','payment_status_after'=>'PENDING','reservation_status_before'=>'ACTIVE','reservation_status_after'=>'RELEASED','revision_before'=>1,'revision_after'=>2,'release_id'=>'4f4ac525-91d1-4d43-8b91-2a0cb8472999','release_fingerprint'=>str_repeat('a',64),'released_at_after'=>self::A,'updated_at_after'=>self::A,'paid_at_after'=>null,'payment_last_event_at_after'=>null,'total_cop'=>100];}
    public function test_payment_after_write_is_absolute_preserves_invariants_and_is_idempotent():void{$client=$this->client();$repo=new CheckoutSheetsRepository($client);$plan=$this->paymentPlan();$repo->writeReleasePaymentAfter($plan);$payment=$repo->readPayments()[0];$this->assertSame('DECLINED',$payment['status']);$this->assertSame(self::A,$payment['updated_at']);$this->assertSame('CARD',$payment['payment_method']);$this->assertSame(100,$payment['amount_in_cents']);$writes=$client->writes;$repo->writeReleasePaymentAfter($plan);$this->assertSame($writes,$client->writes);}
    public function test_order_after_write_is_absolute_and_replay_is_idempotent():void{$client=$this->client();$repo=new CheckoutSheetsRepository($client);$plan=$this->orderPlan();$repo->writeReleaseOrderAfter(2,$plan);$order=$repo->readOrderById(17);$this->assertSame('RELEASED',$order['reservation_status']);$this->assertSame($plan['release_id'],$order['release_id']);$this->assertSame(self::A,$order['updated_at']);$this->assertSame(2,$order['revision']);$writes=$client->writes;$repo->writeReleaseOrderAfter(2,$plan);$this->assertSame($writes,$client->writes);}
    public function test_payment_and_order_mismatch_fail_closed():void{$client=$this->client();$repo=new CheckoutSheetsRepository($client);$plan=$this->paymentPlan();$plan['amount_in_cents']=101;$this->expectException(CheckoutConsistencyException::class);$repo->writeReleasePaymentAfter($plan);}
}
