import { useEffect, useMemo, useRef, useState } from 'react';

const emptyProduct = { name: '', category: '', subcategory: '', presentation: 'Unidad', price: '', inventory: '0', active: '1' };

export function ProductForm({ mode, product, products, saving, error, errors, onCancel, onSubmit }) {
  const [values, setValues] = useState(emptyProduct); const [imageFile, setImageFile] = useState(null); const [previewUrl, setPreviewUrl] = useState(''); const [localErrors, setLocalErrors] = useState({}); const fileInput = useRef(null);
  const categories = useMemo(() => optionsFrom(products, (item) => item.category), [products]);
  const subcategories = useMemo(() => optionsFrom(products.filter((item) => item.category === values.category), (item) => item.subcategory), [products, values.category]);
  useEffect(() => { setValues(product ? { name: product.name || '', category: product.category || '', subcategory: product.subcategory || '', presentation: product.presentation || '', price: String(product.price ?? ''), inventory: String(product.inventory ?? 0), active: product.active ? '1' : '0' } : emptyProduct); setImageFile(null); setLocalErrors({}); }, [product, mode]);
  useEffect(() => { if (!imageFile) { setPreviewUrl(imageUrl(product?.image)); return undefined; } const url = URL.createObjectURL(imageFile); setPreviewUrl(url); return () => URL.revokeObjectURL(url); }, [imageFile, product?.image]);
  const update = (field) => (event) => setValues((current) => ({ ...current, [field]: event.target.value }));
  const submit = (event) => { event.preventDefault(); const next = {}; ['name','category','subcategory','presentation'].forEach((field) => { if (!values[field].trim()) next[field] = 'Este campo es obligatorio.'; }); const price=Number(values.price), inventory=Number(values.inventory); if(!Number.isInteger(price)||price<0)next.price='Ingresa un precio entero igual o mayor a 0.'; if(!Number.isInteger(inventory)||inventory<0)next.inventory='Ingresa un inventario entero igual o mayor a 0.'; setLocalErrors(next); if(Object.keys(next).length)return; onSubmit({...values,price,inventory,active:values.active==='1',expected_revision:product?.revision,image:imageFile}); };
  const fieldError = (field) => localErrors[field] || errors?.[field]?.[0];
  return <aside className='admin-product-drawer' aria-label={mode === 'create' ? 'Nuevo producto' : 'Editar producto'} aria-modal='true' role='dialog'><div className='admin-product-drawer-header'><h2>{mode === 'create' ? 'Nuevo producto' : 'Editar producto'}</h2><button type='button' className='admin-product-drawer-close' onClick={onCancel} disabled={saving} aria-label='Cerrar'>x</button></div><form className='admin-product-form' onSubmit={submit} noValidate>{error && <p className='admin-product-form-error' role='alert'>{error}</p>}<Field label='Nombre' value={values.name} onChange={update('name')} error={fieldError('name')} /><DatalistField label='Categoria' value={values.category} onChange={update('category')} error={fieldError('category')} options={categories} listId='product-categories' /><DatalistField label='Subcategoria' value={values.subcategory} onChange={update('subcategory')} error={fieldError('subcategory')} options={subcategories} listId='product-subcategories' /><Field label='Presentacion' value={values.presentation} onChange={update('presentation')} error={fieldError('presentation')} /><Field label='Precio' type='number' min='0' step='1' value={values.price} onChange={update('price')} error={fieldError('price')} /><Field label='Inventario' type='number' min='0' step='1' value={values.inventory} onChange={update('inventory')} error={fieldError('inventory')} /><label className='admin-product-form-field'><span>Estado inicial</span><select value={values.active} onChange={update('active')}><option value='1'>Activo</option><option value='0'>Inactivo</option></select></label><section className='admin-product-image-field'><span>Imagen del producto</span>{previewUrl && <img src={previewUrl} alt='Vista previa del producto' className='admin-product-image-preview' />}<input ref={fileInput} type='file' accept='image/jpeg,image/png,image/webp' onChange={(event) => setImageFile(event.target.files?.[0] || null)} disabled={saving} /><button type='button' onClick={() => fileInput.current?.click()} disabled={saving}>{mode === 'create' ? 'Seleccionar imagen' : 'Cambiar imagen'}</button><small>JPG, PNG o WEBP. Maximo 5 MB.</small>{fieldError('image') && <small className='admin-product-image-error'>{fieldError('image')}</small>}</section><div className='admin-product-form-actions'><button type='button' onClick={onCancel} disabled={saving}>Cancelar</button><button type='submit' className='is-primary' disabled={saving}>{saving ? 'Guardando...' : mode === 'create' ? 'Crear producto' : 'Guardar cambios'}</button></div></form></aside>;
}
function Field({ label, error, ...props }) { return <label className='admin-product-form-field'><span>{label}</span><input {...props} aria-invalid={Boolean(error)} />{error && <small>{error}</small>}</label>; }
function DatalistField({ label, error, options, listId, ...props }) { return <label className='admin-product-form-field'><span>{label}</span><input {...props} list={listId} aria-invalid={Boolean(error)} /><datalist id={listId}>{options.map((option) => <option key={option} value={option} />)}</datalist>{error && <small>{error}</small>}</label>; }
function optionsFrom(products, value) { return [...new Set(products.map(value).filter(Boolean))].sort((a,b) => a.localeCompare(b,'es')); }
function imageUrl(image) { return !image ? '' : image.startsWith('http') || image.startsWith('/') ? image : `/${image}`; }
