<?php
namespace Tests\Unit\Services;
use App\Exceptions\CheckoutConsistencyException;
use App\Exceptions\CheckoutReleaseException;
use App\Services\CheckoutReleaseVerificationValidator;
use App\Services\CheckoutUtcTimestamp;
use Tests\TestCase;
class CheckoutReleaseVerificationValidatorTest extends TestCase
{
 private function validator():CheckoutReleaseVerificationValidator{return new CheckoutReleaseVerificationValidator(new CheckoutUtcTimestamp);}
 private function payment():array{return ['status'=>'PENDING','wompi_transaction_id'=>'txn-1','updated_at'=>'2026-09-25T12:00:00.100Z'];}
 private function now():\DateTimeImmutable{return new \DateTimeImmutable('2026-09-25T12:00:00.100Z');}
 private function releaseCode(callable $callback):string{try{$callback();$this->fail('Expected release exception.');}catch(CheckoutReleaseException $e){return $e->releaseCode();}}
 public function test_it_accepts_exact_pending_final_verification():void{$r=$this->validator()->validate([$this->payment()],[['wompi_transaction_id'=>'txn-1','status'=>'DECLINED','checked_at'=>'2026-09-25T12:00:00.100Z']],new \DateTimeImmutable('2026-09-25T12:00:00.100Z'));$this->assertSame('DECLINED',$r['txn-1']['status']);}
 public function test_it_rejects_missing_pending_verification():void{$this->expectException(CheckoutReleaseException::class);$this->validator()->validate([$this->payment()],[],new \DateTimeImmutable('2026-09-25T12:00:00.100Z'));}
 public function test_it_rejects_extra_or_old_verification():void{try{$this->validator()->validate([$this->payment()],[['wompi_transaction_id'=>'other','status'=>'ERROR','checked_at'=>'2026-09-25T12:00:00.100Z']],new \DateTimeImmutable('2026-09-25T12:00:00.100Z'));$this->fail();}catch(CheckoutConsistencyException){}$this->expectException(CheckoutConsistencyException::class);$this->validator()->validate([$this->payment()],[['wompi_transaction_id'=>'txn-1','status'=>'ERROR','checked_at'=>'2026-09-25T12:00:00.099Z']],new \DateTimeImmutable('2026-09-25T12:00:00.100Z'));}
 public function test_it_accepts_each_authoritative_final_status_and_exact_boundaries():void{foreach(['DECLINED','VOIDED','ERROR'] as $status){$result=$this->validator()->validate([$this->payment()],[['wompi_transaction_id'=>'txn-1','status'=>$status,'checked_at'=>'2026-09-25T12:10:00.100Z']],$this->now());$this->assertSame($status,$result['txn-1']['status']);}$equal=$this->validator()->validate([$this->payment()],[['wompi_transaction_id'=>'txn-1','status'=>'ERROR','checked_at'=>'2026-09-25T12:00:00.100Z']],$this->now());$this->assertSame('ERROR',$equal['txn-1']['status']);}
 public function test_invalid_final_verification_shapes_are_invalid_request():void{foreach([['status'=>'APPROVED','checked_at'=>'2026-09-25T12:00:00.100Z'],['status'=>'PENDING','checked_at'=>'2026-09-25T12:00:00.100Z'],['status'=>'DECLINED','checked_at'=>'2026-09-25T12:00:00Z'],['status'=>'DECLINED','checked_at'=>'2026-09-25T12:00:00.100+00:00'],['status'=>'DECLINED','checked_at'=>'2026-02-30T12:00:00.100Z'],['status'=>'DECLINED','checked_at'=>'2026-09-25T12:10:00.101Z']] as $case){$this->assertSame('INVALID_REQUEST',$this->releaseCode(fn()=>$this->validator()->validate([$this->payment()],[['wompi_transaction_id'=>'txn-1']+$case],$this->now())));} $this->assertSame('INVALID_REQUEST',$this->releaseCode(fn()=>$this->validator()->validate([$this->payment()],[['wompi_transaction_id'=>'','status'=>'DECLINED','checked_at'=>'2026-09-25T12:00:00.100Z']],$this->now())));}
 public function test_multiple_pending_requires_the_exact_unique_set_in_any_input_order():void{$payments=[['status'=>'PENDING','wompi_transaction_id'=>'a','updated_at'=>'2026-09-25T12:00:00.100Z'],['status'=>'PENDING','wompi_transaction_id'=>'b','updated_at'=>'2026-09-25T12:00:00.100Z']];$verified=[['wompi_transaction_id'=>'b','status'=>'VOIDED','checked_at'=>'2026-09-25T12:00:00.100Z'],['wompi_transaction_id'=>'a','status'=>'DECLINED','checked_at'=>'2026-09-25T12:00:00.100Z']];$this->assertCount(2,$this->validator()->validate($payments,$verified,$this->now()));$this->assertSame('PENDING_PAYMENT_UNVERIFIED',$this->releaseCode(fn()=>$this->validator()->validate($payments,[$verified[0]],$this->now())));$this->assertSame('INVALID_REQUEST',$this->releaseCode(fn()=>$this->validator()->validate($payments,[$verified[0],$verified[0]],$this->now())));}
}
