<?php

namespace Tests\Unit\Services;

use App\Contracts\GoogleSheetsValuesClient;
use App\Exceptions\CheckoutPaymentEventException;
use App\Repositories\CheckoutSheetsRepository;
use App\Services\CheckoutIdSequenceStore;
use App\Services\CheckoutLock;
use App\Services\CheckoutPaymentEventNormalizer;
use App\Services\CheckoutPaymentEventService;
use App\Services\CheckoutPaymentEventStateValidator;
use App\Services\OrderNotificationOutboxStore;
use Tests\TestCase;

final class CheckoutPaymentEventServiceTest extends TestCase
{
    private string $directory;private const T0='2026-09-26T10:00:00.000Z';private const T1='2026-09-26T10:01:00.000Z';private const T2='2026-09-26T10:02:00.000Z';
    protected function setUp():void{parent::setUp();$this->directory=sys_get_temp_dir().DIRECTORY_SEPARATOR.'payment-event-'.bin2hex(random_bytes(5));}
    protected function tearDown():void{foreach(glob($this->directory.'*')?:[] as $file)@unlink($file);parent::tearDown();}
    public function test_normalizer_enforces_literal_input_and_future_boundary():void
    {$n=new CheckoutPaymentEventNormalizer;$now=new \DateTimeImmutable(self::T0);$this->assertSame(self::T0,$n->normalize($this->event(),$now)['event_occurred_at']);$this->assertSame('2026-09-26T10:10:00.000Z',$n->normalize($this->event(['event_occurred_at'=>'2026-09-26T10:10:00.000Z']),$now)['event_occurred_at']);foreach([['currency','USD','CURRENCY_MISMATCH'],['event_occurred_at','2026-09-26T10:10:00.001Z','INVALID_REQUEST'],['event_occurred_at','2026-09-26T10:00:00Z','INVALID_REQUEST'],['status','PAID','INVALID_REQUEST'],['amount_in_cents',0,'INVALID_REQUEST'],['id',str_repeat('x',201),'INVALID_REQUEST']] as [$field,$value,$code]){$e=$this->event([$field=>$value]);try{$n->normalize($e,$now);$this->fail();}catch(CheckoutPaymentEventException $x){$this->assertSame($code,$x->paymentCode);}}}
    public function test_validator_accepts_only_authoritative_order_combinations_and_invariants():void
    {$v=new CheckoutPaymentEventStateValidator;$this->assertSame('PENDING|PENDING|ACTIVE',$v->order($this->order(),'TTV-1')['combination']);foreach([['status'=>'PROCESSING'],['paid_at'=>self::T0],['reservation_status'=>'RELEASED','release_id'=>''],['payment_status'=>'APPROVED','reservation_status'=>'CONSUMED','paid_at'=>'']] as $change){try{$v->order(array_replace($this->order(),$change),'TTV-1');$this->fail();}catch(CheckoutPaymentEventException $e){$this->assertSame('CONSISTENCY_UNCERTAIN',$e->paymentCode);}}}
    public function test_global_payment_duplicate_is_consistency_uncertain_before_write():void
    {$tables=$this->tables([$this->payment(1,'PENDING',self::T0)]);$tables['Pagos'][]=$tables['Pagos'][1];[$service,$client]=$this->service($tables);$result=$service->record($this->event(),new \DateTimeImmutable(self::T1));$this->assertSame('CONSISTENCY_UNCERTAIN',$result['error']['code']);$this->assertSame(0,array_sum($client->writes));}
    public function test_new_payment_generates_internal_id_and_records_non_approved_event():void
    {[$service,$client,$repo,$outbox]=$this->service($this->tables());$r=$service->record($this->event(),new \DateTimeImmutable(self::T1));$this->assertTrue($r['ok']);$this->assertSame(1,$r['data']['payment_attempt_id']);$this->assertSame('RECORDED',$r['data']['event_result']);$this->assertSame([],$outbox->all());$payment=$repo->readPaymentsForPaymentEvent()[0];$this->assertSame(self::T1,$payment['created_at']);$this->assertSame(self::T0,$payment['updated_at']);$order=$repo->readOrdersForPaymentEvent()[0];$this->assertSame(self::T0,$order['payment_last_event_at']);$this->assertSame(2,$order['revision']);$this->assertSame(1,$client->writes['Pagos']);$this->assertSame(1,$client->writes['Pedidos']);}
    public function test_declined_payment_does_not_enqueue_order_created_notification():void
    {[$service,,,$outbox]=$this->service($this->tables());$result=$service->record($this->event(['status'=>'DECLINED']),new \DateTimeImmutable(self::T1));$this->assertSame('RECORDED',$result['data']['event_result']);$this->assertSame([],$outbox->all());}
    public function test_stale_event_has_zero_writes_and_exact_replay_can_complete_order():void
    {$tables=$this->tables([$this->payment(1,'PENDING',self::T1)]);[$service,$client,$repo]=$this->service($tables);$stale=$service->record($this->event(['event_occurred_at'=>self::T0]),new \DateTimeImmutable(self::T2));$this->assertSame('STALE_IGNORED',$stale['data']['event_result']);$this->assertSame(0,array_sum($client->writes));$replay=$service->record($this->event(['status'=>'APPROVED','event_occurred_at'=>self::T1]),new \DateTimeImmutable(self::T2));$this->assertSame('CONSISTENCY_UNCERTAIN',$replay['error']['code']);$this->assertSame('PENDING',$repo->readOrdersForPaymentEvent()[0]['payment_status']);}
    public function test_exact_approved_replay_completes_active_order_without_payment_write():void
    {$tables=$this->tables([$this->payment(1,'APPROVED',self::T1)]);[$service,$client,$repo]=$this->service($tables);$r=$service->record($this->event(['status'=>'APPROVED','event_occurred_at'=>self::T1]),new \DateTimeImmutable(self::T2));$this->assertTrue($r['data']['payment_event_replayed']);$this->assertSame('APPROVED',$r['data']['event_result']);$this->assertSame(0,$client->writes['Pagos']);$this->assertSame(1,$client->writes['Pedidos']);$o=$repo->readOrdersForPaymentEvent()[0];$this->assertSame('CONSUMED',$o['reservation_status']);$this->assertSame(2,$o['revision']);}
    public function test_same_timestamp_different_fields_is_uncertain_and_amount_mismatch_precedes_transaction_lookup():void
    {$tables=$this->tables([$this->payment(1,'PENDING',self::T0)]);[$service,$client]=$this->service($tables);$mismatch=$service->record($this->event(['payment_method'=>'NEQUI']),new \DateTimeImmutable(self::T1));$this->assertSame('CONSISTENCY_UNCERTAIN',$mismatch['error']['code']);$amount=$service->record($this->event(['amount_in_cents'=>101,'event_occurred_at'=>self::T1]),new \DateTimeImmutable(self::T1));$this->assertSame('AMOUNT_MISMATCH',$amount['error']['code']);$this->assertSame(0,array_sum($client->writes));}
    public function test_existing_transaction_for_another_order_is_transaction_conflict():void
    {$tables=$this->tables([$this->payment(1,'PENDING',self::T0)]);$tables['Pedidos'][]=array_values($this->order(['order_id'=>8,'reference'=>'TTV-2']));[$service,$client]=$this->service($tables);$r=$service->record($this->event(['reference'=>'TTV-2','event_occurred_at'=>self::T1]),new \DateTimeImmutable(self::T2));$this->assertSame('TRANSACTION_CONFLICT',$r['error']['code']);$this->assertSame(0,array_sum($client->writes));}
    public function test_newer_pending_event_updates_existing_payment_and_order_last_event():void
    {$tables=$this->tables([$this->payment(1,'PENDING',self::T0)]);[$service,$client,$repo]=$this->service($tables);$r=$service->record($this->event(['event_occurred_at'=>self::T1]),new \DateTimeImmutable(self::T2));$this->assertSame('RECORDED',$r['data']['event_result']);$this->assertSame(1,$client->writes['Pagos']);$this->assertSame(1,$client->writes['Pedidos']);$this->assertSame(self::T1,$repo->readPaymentsForPaymentEvent()[0]['updated_at']);$this->assertSame(self::T1,$repo->readOrdersForPaymentEvent()[0]['payment_last_event_at']);}
    public function test_approved_active_consumed_and_released_transitions_are_literal():void
    {foreach([['ACTIVE','PENDING','PENDING','PENDING','CONSUMED','APPROVED'],['CONSUMED','APPROVED','PENDING','PENDING','CONSUMED','APPROVED'],['RELEASED','PENDING','PENDING','PAYMENT_REVIEW_REQUIRED','RELEASED','PAYMENT_REVIEW_REQUIRED']] as [$reservation,$payment,$status,$expectedStatus,$expectedReservation,$result]){$order=$this->order(['reservation_status'=>$reservation,'payment_status'=>$payment,'status'=>$status]);if($reservation==='RELEASED')$order=$this->released($order);if($reservation==='CONSUMED')$order=array_replace($order,['paid_at'=>self::T0,'payment_last_event_at'=>self::T0]);[$service,,$repo]=$this->service($this->tables([], $order));$r=$service->record($this->event(['status'=>'APPROVED','event_occurred_at'=>self::T1]),new \DateTimeImmutable(self::T2));$o=$repo->readOrdersForPaymentEvent()[0];$this->assertSame($result,$r['data']['event_result']);$this->assertSame($expectedStatus,$o['status']);$this->assertSame($expectedReservation,$o['reservation_status']);$this->assertSame(2,$o['revision']);}}
    public function test_confirmed_approved_payment_enqueues_both_notifications_once_on_replay():void
    {[$service,$client,,$outbox]=$this->service($this->tables());$first=$service->record($this->event(['status'=>'APPROVED','event_occurred_at'=>self::T1]),new \DateTimeImmutable(self::T2));$this->assertTrue($first['ok']);$this->assertSame('APPROVED',$first['data']['event_result']);$this->assertSame(1,$client->writes['Pedidos']);$entries=$outbox->all();$this->assertCount(2,$entries);$this->assertSame('PEDIDO_CREADO:7:customer',$entries[0]['notification_key']);$this->assertSame('PEDIDO_CREADO:7:admin',$entries[1]['notification_key']);$this->assertSame([['product_id'=>1,'product_name'=>'Producto','unit_price_cop'=>1,'quantity'=>1]],$entries[0]['items']);$replay=$service->record($this->event(['status'=>'APPROVED','event_occurred_at'=>self::T1]),new \DateTimeImmutable(self::T2));$this->assertTrue($replay['data']['payment_event_replayed']);$this->assertSame(1,$client->writes['Pedidos']);$this->assertCount(2,$outbox->all());}
    public function test_payment_review_required_does_not_enqueue_order_created_notification():void
    {$order=$this->released($this->order(['reservation_status'=>'RELEASED']));[$service,,,$outbox]=$this->service($this->tables([], $order));$result=$service->record($this->event(['status'=>'APPROVED','event_occurred_at'=>self::T1]),new \DateTimeImmutable(self::T2));$this->assertSame('PAYMENT_REVIEW_REQUIRED',$result['data']['event_result']);$this->assertSame([],$outbox->all());}
    public function test_outbox_write_failure_returns_error_after_sheets_confirmation():void
    {$blocked=$this->directory.'-blocked';file_put_contents($blocked,'not a directory');$outbox=new OrderNotificationOutboxStore($blocked.'/outbox.json');[$service,,$repo]=$this->service($this->tables(),$outbox);$result=$service->record($this->event(['status'=>'APPROVED','event_occurred_at'=>self::T1]),new \DateTimeImmutable(self::T2));$this->assertFalse($result['ok']);$this->assertSame('INTERNAL_ERROR',$result['error']['code']);$order=$repo->readOrdersForPaymentEvent()[0];$this->assertSame('PENDING',$order['status']);$this->assertSame('APPROVED',$order['payment_status']);$this->assertSame('CONSUMED',$order['reservation_status']);}
    public function test_stored_approved_newer_declined_preserves_payment_but_uses_incoming_for_order_plan():void
    {$tables=$this->tables([$this->payment(1,'APPROVED',self::T0,'CARD')],$this->order(['payment_status'=>'APPROVED','reservation_status'=>'CONSUMED','paid_at'=>self::T0,'payment_last_event_at'=>self::T0]));[$service,$client,$repo]=$this->service($tables);$r=$service->record($this->event(['status'=>'DECLINED','payment_method'=>'NEQUI','event_occurred_at'=>self::T1]),new \DateTimeImmutable(self::T2));$p=$repo->readPaymentsForPaymentEvent()[0];$o=$repo->readOrdersForPaymentEvent()[0];$this->assertSame('RECORDED',$r['data']['event_result']);$this->assertSame('APPROVED',$p['status']);$this->assertSame('CARD',$p['payment_method']);$this->assertSame(self::T1,$p['updated_at']);$this->assertSame(self::T1,$o['payment_last_event_at']);$this->assertSame(1,$client->writes['Pagos']);}
    private function event(array $replace=[]):array{return ['transaction'=>array_replace(['id'=>'tx-1','reference'=>'TTV-1','status'=>'PENDING','payment_method'=>'CARD','amount_in_cents'=>100,'currency'=>'COP','event_occurred_at'=>self::T0],$replace)];}
    private function order(array $replace=[]):array{return array_replace(['order_id'=>7,'reference'=>'TTV-1','status'=>'PENDING','payment_status'=>'PENDING','reservation_status'=>'ACTIVE','reservation_expires_at'=>'2026-09-26T11:00:00.000Z','paid_at'=>'','payment_last_event_at'=>'','checkout_idempotency_key'=>'k','checkout_payload_hash'=>str_repeat('a',64),'release_id'=>'','release_fingerprint'=>'','released_at'=>'','customer_name'=>'N','customer_email'=>'a@b.co','customer_phone'=>'1','customer_document'=>'1','address'=>'A','extra'=>'','city'=>'C','region'=>'R','postal'=>'','total_cop'=>1,'created_at'=>self::T0,'updated_at'=>self::T0,'revision'=>1],$replace);}
    private function released(array $order):array{return array_replace($order,['release_id'=>'4f4ac525-91d1-4d43-8b91-2a0cb8472999','release_fingerprint'=>str_repeat('b',64),'released_at'=>self::T0]);}
    private function payment(int $id,string $status,string $updated,string $method='CARD'):array{return [$id,7,'tx-1',$status,$method,100,'COP',self::T0,$updated];}
    private function tables(array $payments=[],?array $order=null):array{return ['Pedidos'=>[array_keys($this->order()),array_values($order??$this->order())],'PedidoItems'=>[['order_item_id','order_id','product_id','product_name','unit_price_cop','quantity','created_at'],[1,7,1,'Producto',1,1,self::T0]],'Pagos'=>[array_keys(['payment_attempt_id'=>1,'order_id'=>7,'wompi_transaction_id'=>'tx','status'=>'PENDING','payment_method'=>'CARD','amount_in_cents'=>100,'currency'=>'COP','created_at'=>self::T0,'updated_at'=>self::T0]),...$payments]];}
    private function service(array $tables,?OrderNotificationOutboxStore $outbox=null):array{$client=new class($tables) implements GoogleSheetsValuesClient{public array $writes=['Pedidos'=>0,'Pagos'=>0];public function __construct(public array $tables){}public function getValues(string $range):array{return [];}public function batchGetValues(array $ranges):array{return array_map(function($range){$sheet=strtok($range,'!');return str_ends_with($range,'1:1')?[$this->tables[$sheet][0]]:$this->tables[$sheet];},$ranges);}public function updateValues(string $range,array $values):array{preg_match('/^([^!]+)!A(\d+):/',$range,$m);$this->writes[$m[1]]++;$this->tables[$m[1]][(int)$m[2]-1]=$values[0];return [];}public function appendValues(string $range,array $values):array{$this->writes['Pagos']++;foreach($values as $v)$this->tables['Pagos'][]=$v;return [];}public function batchUpdateValues(array $data):array{return [];}};$repo=new CheckoutSheetsRepository($client);$outbox??=new OrderNotificationOutboxStore($this->directory.'.notifications.json');$service=new CheckoutPaymentEventService(new CheckoutLock,$repo,new CheckoutIdSequenceStore($this->directory.'.json'),$outbox);return [$service,$client,$repo,$outbox];}
}
