<?php

namespace Tests\Unit\Services;

use App\Exceptions\CheckoutConsistencyException;
use App\Services\CheckoutReleaseJournalStore;
use Tests\TestCase;

final class CheckoutReleaseJournalStoreTest extends TestCase
{
    private string $directory;
    protected function setUp():void{parent::setUp();$this->directory=sys_get_temp_dir().DIRECTORY_SEPARATOR.'release-journal-'.bin2hex(random_bytes(5));}
    protected function tearDown():void{foreach(glob($this->directory.DIRECTORY_SEPARATOR.'*')?:[] as $file)@unlink($file);@rmdir($this->directory);parent::tearDown();}
    private function store():CheckoutReleaseJournalStore{return new CheckoutReleaseJournalStore($this->directory);}
    private function journal():array{$t='2026-09-25T12:00:00.123Z';return ['version'=>2,'reference'=>'TTV-TEST','order_id'=>17,'expected_revision'=>1,'release_id'=>'4f4ac525-91d1-4d43-8b91-2a0cb8472999','release_fingerprint'=>str_repeat('a',64),'stage'=>'PREPARED','created_at'=>$t,'updated_at'=>$t,'products'=>[['product_id'=>7,'row_number'=>2,'inventory_before'=>0,'inventory_after'=>2,'revision_before'=>1,'revision_after'=>2,'updated_at_before'=>null,'updated_at_after'=>$t]],'payments'=>[['payment_attempt_id'=>1,'order_id'=>17,'wompi_transaction_id'=>'tx-1','status_before'=>'PENDING','status_after'=>'DECLINED','payment_method'=>'CARD','amount_in_cents'=>100,'currency'=>'COP','created_at'=>$t,'updated_at_before'=>$t,'updated_at_after'=>$t]],'expected_order'=>['order_id'=>17,'reference'=>'TTV-TEST','status_before'=>'PENDING','status_after'=>'PENDING','payment_status_before'=>'PENDING','payment_status_after'=>'PENDING','reservation_status_before'=>'ACTIVE','reservation_status_after'=>'RELEASED','revision_before'=>1,'revision_after'=>2,'release_id'=>'4f4ac525-91d1-4d43-8b91-2a0cb8472999','release_fingerprint'=>str_repeat('a',64),'released_at_after'=>$t,'updated_at_after'=>$t,'paid_at_after'=>null,'payment_last_event_at_after'=>null,'total_cop'=>100]];}
    public function test_it_persists_the_complete_pii_free_schema_and_retains_finalized():void{$store=$this->store();$store->create('TTV-TEST',$this->journal());foreach(['PRODUCTS_WRITTEN','PAYMENTS_WRITTEN','ORDER_WRITTEN','FINALIZED'] as $stage)$store->advance('TTV-TEST',$stage);$loaded=$store->load('TTV-TEST');$this->assertSame('FINALIZED',$loaded['stage']);$this->assertNull($loaded['products'][0]['updated_at_before']);$this->assertSame('DECLINED',$loaded['payments'][0]['status_after']);$raw=(string)file_get_contents($this->directory.DIRECTORY_SEPARATOR.hash('sha256','TTV-TEST').'.json');foreach(['customer_name','customer_email','phone','document','address','city','region','postal','extra'] as $pii)$this->assertStringNotContainsString($pii,$raw);}
    public function test_it_accepts_canonical_product_before_timestamp_but_rejects_invalid_schema():void{$journal=$this->journal();$journal['products'][0]['updated_at_before']='2026-09-25T11:00:00.000Z';$this->store()->create('TTV-TEST',$journal);$cases=[fn(&$j)=>$j['release_id']='bad',fn(&$j)=>$j['release_fingerprint']='bad',fn(&$j)=>$j['products'][0]['updated_at_after']='bad',fn(&$j)=>$j['products'][]=$j['products'][0],fn(&$j)=>$j['payments'][]=$j['payments'][0],fn(&$j)=>$j['stage']='UNKNOWN',fn(&$j)=>$j['products'][0]['revision_after']=9,fn(&$j)=>$j['products'][0]['inventory_after']=-1];foreach($cases as $mutate){$j=$this->journal();$mutate($j);try{(new CheckoutReleaseJournalStore($this->directory.'-'.bin2hex(random_bytes(2))))->create('TTV-TEST',$j);$this->fail('Expected invalid journal.');}catch(CheckoutConsistencyException){$this->addToAssertionCount(1);}}}
    public function test_it_rejects_skipped_backwards_and_finalized_transitions():void{$s=$this->store();$s->create('TTV-TEST',$this->journal());foreach(['PAYMENTS_WRITTEN','FINALIZED'] as $invalid){try{$s->advance('TTV-TEST',$invalid);$this->fail();}catch(CheckoutConsistencyException){$this->addToAssertionCount(1);}}$s->advance('TTV-TEST','PRODUCTS_WRITTEN');try{$s->advance('TTV-TEST','PREPARED');$this->fail();}catch(CheckoutConsistencyException){$this->addToAssertionCount(1);}}
}
