<?php

namespace Tests\Unit\Services;

use App\Contracts\GoogleSheetsValuesClient;
use App\Exceptions\CheckoutConsistencyException;
use App\Repositories\CheckoutSheetsRepository;
use App\Services\CheckoutExpiredReservationReleaseService;
use App\Services\CheckoutLock;
use App\Services\CheckoutReleaseFingerprint;
use App\Services\CheckoutReleaseFaultInjector;
use App\Services\CheckoutReleaseJournalStore;
use App\Services\CheckoutUtcTimestamp;
use Tests\TestCase;

final class CheckoutReleaseRecoveryStageTest extends TestCase
{
    private string $directory; private const B='2026-09-25T12:00:00.111Z'; private const A='2026-09-25T12:20:00.111Z';
    protected function setUp():void{parent::setUp();$this->directory=sys_get_temp_dir().DIRECTORY_SEPARATOR.'release-stage-'.bin2hex(random_bytes(5));}
    protected function tearDown():void{foreach(glob($this->directory.DIRECTORY_SEPARATOR.'*')?:[] as $f)@unlink($f);@rmdir($this->directory);parent::tearDown();}
    public function test_prepared_mixed_products_completes_absolute_after_without_over_restoring():void{[$service,$store,$client,$repo]=$this->fixture('PREPARED','mixed','after','before',true);$result=$service->release('TTV-STAGE',1,[],new \DateTimeImmutable(self::A));$this->assertSame('RELEASED',$result['result']);$this->assertSame(3,$client->writes['Productos']);$this->assertSame(0,$client->writes['Pagos']);$this->assertSame(1,$client->writes['Pedidos']);foreach($repo->readProducts() as $p){$this->assertSame(3,$p['inventory']);$this->assertSame(2,$p['revision']);}$this->assertSame('FINALIZED',$store->load('TTV-STAGE')['stage']);}
    public function test_after_products_written_fault_leaves_products_written_and_retry_never_rewrites_products():void
    {
        $fault=new class extends CheckoutReleaseFaultInjector {public function after(string $checkpoint):void{if($checkpoint==='release.after-products-written')throw new \RuntimeException('fault');}};
        [$service,$store,$client,$repo]=$this->fixture('PREPARED','before','before','before',true,$fault);
        try{$service->release('TTV-STAGE',1,[],new \DateTimeImmutable(self::A));$this->fail('Expected fault.');}catch(\RuntimeException $e){$this->assertSame('fault',$e->getMessage());}
        $planned=$store->load('TTV-STAGE');$this->assertSame('PRODUCTS_WRITTEN',$planned['stage']);
        foreach($repo->readProducts() as $product){$this->assertSame(3,$product['inventory']);$this->assertSame(2,$product['revision']);$this->assertSame(self::A,$product['updated_at']);}
        $order=$repo->readOrderById(17);$this->assertSame('ACTIVE',$order['reservation_status']);$this->assertSame(1,$order['revision']);
        $releaseId=$planned['release_id'];$fingerprint=$planned['release_fingerprint'];$releasedAt=$planned['expected_order']['released_at_after'];
        $client->writes=['Productos'=>0,'Pagos'=>0,'Pedidos'=>0];$result=$service->release('TTV-STAGE',1,[],new \DateTimeImmutable(self::A));
        $this->assertSame('RELEASED',$result['result']);$this->assertSame(0,$client->writes['Productos']);$this->assertSame(2,$client->writes['Pagos']);$this->assertSame(1,$client->writes['Pedidos']);
        $final=$store->load('TTV-STAGE');$this->assertSame('FINALIZED',$final['stage']);$this->assertSame($releaseId,$final['release_id']);$this->assertSame($fingerprint,$final['release_fingerprint']);$this->assertSame($releasedAt,$final['expected_order']['released_at_after']);
    }
    public function test_after_payments_written_fault_leaves_payments_written_and_retry_only_writes_order():void
    {
        $fault=new class extends CheckoutReleaseFaultInjector {public function after(string $checkpoint):void{if($checkpoint==='release.after-payments-written')throw new \RuntimeException('fault');}};
        [$service,$store,$client,$repo]=$this->fixture('PREPARED','before','before','before',false,$fault);
        try{$service->release('TTV-STAGE',1,[],new \DateTimeImmutable(self::A));$this->fail('Expected fault.');}catch(\RuntimeException $e){$this->assertSame('fault',$e->getMessage());}
        $planned=$store->load('TTV-STAGE');$this->assertSame('PAYMENTS_WRITTEN',$planned['stage']);
        $payment=$repo->readPayments()[0];$this->assertSame('DECLINED',$payment['status']);$this->assertSame(self::A,$payment['updated_at']);
        $order=$repo->readOrderById(17);$this->assertSame('ACTIVE',$order['reservation_status']);$this->assertSame(1,$order['revision']);
        $releaseId=$planned['release_id'];$fingerprint=$planned['release_fingerprint'];$releasedAt=$planned['expected_order']['released_at_after'];
        $client->writes=['Productos'=>0,'Pagos'=>0,'Pedidos'=>0];$result=$service->release('TTV-STAGE',1,[],new \DateTimeImmutable(self::A));
        $this->assertSame('RELEASED',$result['result']);$this->assertSame(0,$client->writes['Productos']);$this->assertSame(0,$client->writes['Pagos']);$this->assertSame(1,$client->writes['Pedidos']);
        $final=$store->load('TTV-STAGE');$this->assertSame('FINALIZED',$final['stage']);$this->assertSame($releaseId,$final['release_id']);$this->assertSame($fingerprint,$final['release_fingerprint']);$this->assertSame($releasedAt,$final['expected_order']['released_at_after']);
    }
    public function test_products_written_never_rewrites_inventory_and_completes_mixed_payments():void{[$service,$store,$client,$repo]=$this->fixture('PRODUCTS_WRITTEN','after','mixed','before');$service->release('TTV-STAGE',1,[],new \DateTimeImmutable(self::A));$this->assertSame(0,$client->writes['Productos']);$this->assertSame(1,$client->writes['Pagos']);$this->assertSame(1,$client->writes['Pedidos']);foreach($repo->readPayments() as $p)$this->assertSame('DECLINED',$p['status']);$this->assertSame('FINALIZED',$store->load('TTV-STAGE')['stage']);}
    public function test_payments_written_writes_only_order_before_to_after():void{[$service,$store,$client]=$this->fixture('PAYMENTS_WRITTEN','after','after','before');$service->release('TTV-STAGE',1,[],new \DateTimeImmutable(self::A));$this->assertSame(0,$client->writes['Productos']);$this->assertSame(0,$client->writes['Pagos']);$this->assertSame(1,$client->writes['Pedidos']);$this->assertSame('FINALIZED',$store->load('TTV-STAGE')['stage']);}
    public function test_order_written_and_finalized_are_replays_without_writes_or_delete():void{foreach(['ORDER_WRITTEN','FINALIZED'] as $stage){[$service,$store,$client]=$this->fixture($stage,'after','after','after');$result=$service->release('TTV-STAGE',1,[],new \DateTimeImmutable(self::A));$this->assertSame('REPLAY',$result['result']);$this->assertSame(0,array_sum($client->writes));$this->assertSame('FINALIZED',$store->load('TTV-STAGE')['stage']);$store->delete('TTV-STAGE');}}
    public function test_invalid_stage_row_fails_closed_without_advancing():void{[$service,$store,$client]=$this->fixture('PRODUCTS_WRITTEN','before','before','before');try{$service->release('TTV-STAGE',1,[],new \DateTimeImmutable(self::A));$this->fail();}catch(CheckoutConsistencyException){$this->addToAssertionCount(1);}$this->assertSame('PRODUCTS_WRITTEN',$store->load('TTV-STAGE')['stage']);$this->assertSame(0,array_sum($client->writes));}
    /** @return array{0:CheckoutExpiredReservationReleaseService,1:CheckoutReleaseJournalStore,2:object,3:CheckoutSheetsRepository} */
    private function fixture(string $stage,string $productState,string $paymentState,string $orderState,bool $threeProducts=false,?CheckoutReleaseFaultInjector $fault=null):array
    {$journal=$this->journal($stage,$threeProducts);$tables=$this->tables($journal,$productState,$paymentState,$orderState);$client=new class($tables) implements GoogleSheetsValuesClient {public array $writes=['Productos'=>0,'Pagos'=>0,'Pedidos'=>0];public function __construct(public array $tables){}public function getValues(string $r):array{return [];}public function batchGetValues(array $ranges):array{return array_map(function($r){$s=explode('!',$r)[0];return str_ends_with($r,'1:1')?[array_values($this->tables[$s][0])]:$this->tables[$s];},$ranges);}public function updateValues(string $range,array $values):array{preg_match('/^([^!]+)!A(\d+):/',$range,$m);$this->writes[$m[1]]++;$this->tables[$m[1]][(int)$m[2]-1]=$values[0];return [];}public function appendValues(string $r,array $v):array{return [];}public function batchUpdateValues(array $d):array{return [];}};$store=new CheckoutReleaseJournalStore($this->directory,new CheckoutUtcTimestamp);$store->create('TTV-STAGE',$journal);$repo=new CheckoutSheetsRepository($client);$service=new CheckoutExpiredReservationReleaseService(new CheckoutLock,$repo,$store,new CheckoutReleaseFingerprint,new CheckoutUtcTimestamp,null,null,null,$fault);return [$service,$store,$client,$repo];}
    private function journal(string $stage,bool $three=false):array{$products=[];foreach($three?[7,8,9]:[7] as $i=>$id)$products[]=['product_id'=>$id,'row_number'=>$i+2,'inventory_before'=>1,'inventory_after'=>3,'revision_before'=>1,'revision_after'=>2,'updated_at_before'=>self::B,'updated_at_after'=>self::A];$payments=[];foreach([1,2] as $id)$payments[]=['row_number'=>$id+1,'payment_attempt_id'=>$id,'order_id'=>17,'wompi_transaction_id'=>'tx-'.$id,'status_before'=>'PENDING','status_after'=>'DECLINED','payment_method'=>'CARD','amount_in_cents'=>100,'currency'=>'COP','created_at'=>self::B,'updated_at_before'=>self::B,'updated_at_after'=>self::A];return ['version'=>2,'reference'=>'TTV-STAGE','order_id'=>17,'expected_revision'=>1,'release_id'=>'4f4ac525-91d1-4d43-8b91-2a0cb8472999','release_fingerprint'=>str_repeat('a',64),'stage'=>$stage,'created_at'=>self::A,'updated_at'=>self::A,'products'=>$products,'payments'=>$payments,'expected_order'=>['order_id'=>17,'reference'=>'TTV-STAGE','status_before'=>'PENDING','status_after'=>'PENDING','payment_status_before'=>'PENDING','payment_status_after'=>'PENDING','reservation_status_before'=>'ACTIVE','reservation_status_after'=>'RELEASED','revision_before'=>1,'revision_after'=>2,'release_id'=>'4f4ac525-91d1-4d43-8b91-2a0cb8472999','release_fingerprint'=>str_repeat('a',64),'released_at_after'=>self::A,'updated_at_after'=>self::A,'paid_at_after'=>null,'payment_last_event_at_after'=>null,'total_cop'=>100]];}
    private function tables(array $j,string $ps,string $qs,string $os):array{$h=self::B;$products=[['product_id','category','subcategory','name','presentation','price_cop','inventory','active','image_path','legacy_img','created_at','updated_at','revision']];foreach($j['products'] as $p){$after=$ps==='after'||($ps==='mixed'&&$p['product_id']===8);$products[]=[$p['product_id'],'C','S','P','U',100,$after?3:1,true,'','',$h,$after?self::A:$h,$after?2:1];}$payments=[['payment_attempt_id','order_id','wompi_transaction_id','status','payment_method','amount_in_cents','currency','created_at','updated_at']];foreach($j['payments'] as $p){$after=$qs==='after'||($qs==='mixed'&&$p['payment_attempt_id']===2);$payments[]=[$p['payment_attempt_id'],17,$p['wompi_transaction_id'],$after?'DECLINED':'PENDING','CARD',100,'COP',$h,$after?self::A:$h];}$after=$os==='after';$orders=[['order_id','reference','status','payment_status','reservation_status','reservation_expires_at','paid_at','payment_last_event_at','checkout_idempotency_key','checkout_payload_hash','release_id','release_fingerprint','released_at','customer_name','customer_email','customer_phone','customer_document','address','extra','city','region','postal','total_cop','created_at','updated_at','revision'],[17,'TTV-STAGE','PENDING','PENDING',$after?'RELEASED':'ACTIVE','2026-09-25T12:10:00.111Z','','','11111111-1111-4111-8111-111111111111',str_repeat('b',64),$after?$j['release_id']:'',$after?$j['release_fingerprint']:'',$after?self::A:'','N','a@b.co','1','1','D','','C','R','',100,$h,$after?self::A:$h,$after?2:1]];return ['Productos'=>$products,'Pedidos'=>$orders,'PedidoItems'=>[['order_item_id','order_id','product_id','product_name','unit_price_cop','quantity','created_at']],'Pagos'=>$payments];}
}
