<?php

namespace Tests\Unit\Services;

use App\Exceptions\CheckoutConsistencyException;
use App\Services\CheckoutReleasePaymentStateClassifier;
use App\Services\CheckoutReleaseProductStateClassifier;
use App\Services\CheckoutUtcTimestamp;
use Tests\TestCase;

final class CheckoutReleaseStateClassifierTest extends TestCase
{
    private const B='2026-09-25T12:00:00.111Z'; private const A='2026-09-25T12:10:00.111Z';
    private function product():array{return ['product_id'=>7,'row_number'=>2,'inventory_before'=>1,'inventory_after'=>3,'revision_before'=>4,'revision_after'=>5,'updated_at_before'=>null,'updated_at_after'=>self::A];}
    private function payment():array{return ['row_number'=>2,'payment_attempt_id'=>1,'order_id'=>17,'wompi_transaction_id'=>'tx-1','status_before'=>'PENDING','status_after'=>'DECLINED','payment_method'=>'CARD','amount_in_cents'=>100,'currency'=>'COP','created_at'=>self::B,'updated_at_before'=>self::B,'updated_at_after'=>self::A];}
    public function test_product_classifier_is_literal_and_rejects_non_before_after_identity():void{$c=new CheckoutReleaseProductStateClassifier(new CheckoutUtcTimestamp);$p=$this->product();$this->assertSame('BEFORE',$c->classify(['product_id'=>7,'sheet_row'=>2,'inventory'=>1,'revision'=>4,'updated_at'=>self::A],$p));$this->assertSame('AFTER',$c->classify(['product_id'=>7,'sheet_row'=>2,'inventory'=>3,'revision'=>5,'updated_at'=>self::B],$p));foreach([['inventory'=>2,'revision'=>4],['inventory'=>1,'revision'=>6],['product_id'=>8,'inventory'=>1,'revision'=>4],['sheet_row'=>3,'inventory'=>1,'revision'=>4]] as $mutation){$row=array_replace(['product_id'=>7,'sheet_row'=>2,'inventory'=>1,'revision'=>4,'updated_at'=>self::B],$mutation);try{$c->classify($row,$p);$this->fail('Expected mismatch.');}catch(CheckoutConsistencyException){$this->addToAssertionCount(1);}}}
    public function test_payment_classifier_requires_all_invariants_and_exact_timestamp():void{$c=new CheckoutReleasePaymentStateClassifier(new CheckoutUtcTimestamp);$p=$this->payment();$before=['payment_attempt_id'=>1,'order_id'=>17,'wompi_transaction_id'=>'tx-1','status'=>'PENDING','payment_method'=>'CARD','amount_in_cents'=>100,'currency'=>'COP','created_at'=>self::B,'updated_at'=>self::B];$after=$before;$after['status']='DECLINED';$after['updated_at']=self::A;$this->assertSame('BEFORE',$c->classify($before,$p));$this->assertSame('AFTER',$c->classify($after,$p));foreach(['status'=>'ERROR','updated_at'=>self::A,'wompi_transaction_id'=>'other','amount_in_cents'=>101,'currency'=>'USD','payment_method'=>'CASH','created_at'=>self::A] as $field=>$value){$broken=$before;$broken[$field]=$value;try{$c->classify($broken,$p);$this->fail('Expected mismatch for '.$field);}catch(CheckoutConsistencyException){$this->addToAssertionCount(1);}}}
    public function test_mixed_rows_are_independently_demonstrable():void{$pc=new CheckoutReleaseProductStateClassifier(new CheckoutUtcTimestamp);$qc=new CheckoutReleasePaymentStateClassifier(new CheckoutUtcTimestamp);$a=$this->product();$b=$a;$b['product_id']=8;$b['row_number']=3;$this->assertSame('BEFORE',$pc->classify(['product_id'=>7,'sheet_row'=>2,'inventory'=>1,'revision'=>4,'updated_at'=>self::B],$a));$this->assertSame('AFTER',$pc->classify(['product_id'=>8,'sheet_row'=>3,'inventory'=>3,'revision'=>5,'updated_at'=>self::B],$b));$p=$this->payment();$q=$p;$q['payment_attempt_id']=2;$q['wompi_transaction_id']='tx-2';$before=['payment_attempt_id'=>1,'order_id'=>17,'wompi_transaction_id'=>'tx-1','status'=>'PENDING','payment_method'=>'CARD','amount_in_cents'=>100,'currency'=>'COP','created_at'=>self::B,'updated_at'=>self::B];$after=$before;$after['payment_attempt_id']=2;$after['wompi_transaction_id']='tx-2';$after['status']='DECLINED';$after['updated_at']=self::A;$this->assertSame('BEFORE',$qc->classify($before,$p));$this->assertSame('AFTER',$qc->classify($after,$q));}
}
